### ISSUE TITLE
Need more API code samples using bash and curl

### ISSUE THREAD

**Issue by shreyas-agnihotri** [VeritasOS/netbackup-api-code-samples#1]

**Comment by ghost** [comment]
I will try adding code samples using using curl.

**Comment by ghost** [comment]
do we need curl command line or using curl with cpp?

**Comment by shreyas-agnihotri** [comment]
Command line with curl would be great. Thanks!

**Comment by shreyas-agnihotri** [comment]
Merged API code samples using curl for `get_nb_images.sh` and `get_nb_jobs.sh`
