### ISSUE TITLE
create policy error

### ISSUE THREAD

**Issue by junfenglu2016** [VeritasOS/netbackup-api-code-samples#24]
python3 -W ignore create_policy_step_by_step.py -nbmaster 10.96.93.74 -username root -password mko0,lp- -domainName eccbackup03 -domainType unixpwd           
-------------------------------------------------------------------------------------------------
--                          This script requires Python3.5 or higher.                          --
--    If your current system does not have Python3.5 or higher installed, this will not work.  --
-------------------------------------------------------------------------------------------------

Executing this library requires some additional python3.5 libraries like 
        'requests'.

You will, however, require 'requests' library to make the API calls.

You can install the dependent libraries using the following commands: 
pip install requests 
-------------------------------------------------------------------------------------------------

You can specify the 'nbmaster', 'username', 'password', 'domainName' and 'domainType' as command-line parameters

Example:
python -W ignore create_policy_step_by_step.py -nbmaster <masterServer> -username <username> -password <password> [-domainName <domainName>] [-domainType <domainType>]

Making POST Request to login for user 'root'

The response code of the Login API: 201

Making POST Request to create VMware Policy with defaults 

Create Policy API with defaults failed with status code 400 and {'errorMessage': 'Error response from bpdbm: invalid command parameter', 'errorCode': 20, 'details': {}}

 VMware_test_policy with defaults is created with status code : 400

Making GET Request to list policies 

List policy succeeded with status code: 200

Traceback (most recent call last):
  File "create_policy_step_by_step.py", line 82, in <module>
    policy_api_requests.get_netbackup_policies(jwt, base_url)
  File "/root/netbackup-api-code-samples/recipes/python/policy_api_requests.py", line 241, in get_netbackup_policies
    print("\n Json Response body for List policies  : \n{}\n".format(json.loads(resp.content)))
  File "/usr/python3/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by akumar91** [comment]
could you please share the OS you are running the script on?
Also the Netbackup version you have installed along with python version please?

The script has been tested on windows and works as expected. We will investigate further with the issue once we know the details.

Thanks

**Comment by junfenglu2016** [comment]
OS version is : SUSE Linux Enterprise Server for SAP Applications 12 SP3  (x86_64)
NBU version is :8.1.2

I solved this problem by reinstalling nbu master.

but there is still one problem, i can't always get Authentication token with sericuty admin role, it will report error after trying a few times. there is no problem to use root account get the token

**Comment by akumar91** [comment]
Does the login actually succeeds but all of the requests fail with unauthorized. The security admin role does not grant access to policy APIs.

Would you mind sharing the output of your script when you tried with security admin credentials?

Also would appreciate the failed instance of the script.

I will run the script at the same with security admin role on my end

**Comment by junfenglu2016** [comment]
**first time :** 
curl --request POST \
  --url https://10.96.93.74:1556/netbackup/login \
  --header 'content-type: application/vnd.netbackup+json;version=1.0' \
  --data '{                                         
            "domainType":"unixpwd",                                 
            "domainName":"eccbackup03",                             
            "userName":"somerbacuser",                            
            "password":"somerbacpass" 
}'
result is : 
{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJuYnVfbWFzdGVyIiwianRpIjoiMGE2ZjljMTEtNzZhNi00YjUzLWEzNWUtYjEwZGUwMWQ5YTA2IiwiaWF0IjoxNTQzODg1OTEwMzkyLCJleHAiOjE1NDM5NzIzMTAzOTEsInN1YiI6ImVjY2JhY2t1cDAzOnJiYWNhZG1pbjp1bml4cHdkIiwiYXV0aF90b2tlbiI6IjBhNmY5YzExLTc2YTYtNGI1My1hMzVlLWIxMGRlMDFkOWEwNiIsImlzX2FkbWluIjoiZmFsc2UiLCJpc19tYWNoaW5lIjoiZmFsc2UiLCJ0b2tlbl90eXBlIjoiU0VTU0lPTiJ9.Zv6DlObBx6kQMym9Cg0HRwlBIe1RGlVF0iu34OUT1gQ1PlgREYg-eJYrowAZiXm9UkkTKy5rAURHpQRvkTuPSM2s8DpoggZVGriooLAbvvrbR4erDAwJo5GDVUe_AIM2YmgjJnAMyINKTxtRM9R74vplk8qqdunkMO2tYhkMpaw",
  "tokenType": "BEARER",
  "validity": 86400
}

**the second the same command** 

i got this error : 
{
  "errorCode": 160,
  "errorMessage": "authentication failed",
  "details": {}
}

but this command always success, use root

curl --request POST \
  --url https://10.96.93.74:1556/netbackup/login \
  --header 'content-type: application/vnd.netbackup+json;version=1.0' \
  --data '{                                         
            "domainType":"unixpwd",                                 
            "domainName":"eccbackup03",                             
            "userName":"somerootuser",                            
            "password":"somerootpass" 
}'

**Comment by DigPVB** [comment]
@junfenglu2016 </br>

Please do not put username and password in your communication. There are multiple bots that do nothing but scour github for root and password so it can be used for malicious purposes...

**Comment by akumar91** [comment]
I shared this additional information with teams who worked with login API and we are looking through the issue. Thank you for your patience.
