### ISSUE TITLE
Need more API code samples using Go

### ISSUE THREAD

**Issue by shreyas-agnihotri** [VeritasOS/netbackup-api-code-samples#3]

**Comment by bhardwaj-aditya** [comment]
I'll take care of it.

**Comment by sgupta03** [comment]
I will assign it to myself as I have some code ready for go language.

**Comment by srnavale** [comment]
Redacted has checked in a couple of Go scripts:
https://github.com/VeritasOS/netbackup-api-code-samples/pull/13
