### ISSUE TITLE
Condition set for adding TLS12  will always be true

### ISSUE THREAD

**Issue by brajesh-dubey** [VeritasOS/netbackup-api-code-samples#41]
Condition used for adding TLS12 in security protocol is incorrectly placed and will always be true basis the code published. 
-notcontains is incorrectly used here, this will become false only when Tls12 is the only defined security protocol in that system. so, the condition makes no sense in the code. I saw this in netbackup-api-code-samples/snippets/powershell/Get-NB-Jobs.ps1 line number 46. The same issue is with all powershell codes. Please review it.

**Comment by santhosh-vrts** [comment]
#42
