### ISSUE TITLE
Curl example gives http 400 bad request error due to page limit

### ISSUE THREAD

**Issue by LWDArjan** [VeritasOS/netbackup-api-code-samples#51]
I have a script based on the curl example for getting a job list and it started giving http 400 errors since the update to NB 8.1.2.
Turns out that specifying the 2nd post for 'page[limit]=##'  causes this error.
Unsure if this is due to a bug in 8.1.2 or a change in the API (or something else)

**Comment by ghost** [comment]
looking into this

**Comment by ghost** [comment]
This issue is fixed. Please use latest samples.
