### ISSUE TITLE
Vmware workflow with protection plans

### ISSUE THREAD

**Issue by ntbritton** [VeritasOS/netbackup-api-code-samples#67]
I dont see any examples and i am not seeing a way to make the link that i am missing.

I am doing it via ansible and have two plays.  One will create the asset groups for our standards and the other will create the protection plans with a specific naming standard for our purposes.  

My thought was that there would then be a call to link the asset group to the protection plan, but i am not seeing how i could do that.    Any thoughts?     I can take an example from most languages and convert that to ansible.   Its just a uri call in ansible.

**Comment by ntbritton** [comment]
I put a couple examples of my include plays in my fork and requested the be added..  If there is a different way you prefer i share that work let me know.

**Comment by jaya-korlepara** [comment]
You can use the /slos/{sloID}/subscriptions API to create a subscription to the protection plan.

Refer to the NetBackup Service Catalog API documentation - https://sort.veritas.com/public/documents/nbu/8.2/windowsandunix/productguides/html/servicecatalog_api/#/default/post_slos__sloID__subscriptions

**Comment by ntbritton** [comment]
jaya-korlepara - was correct.
