### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KavyaKanya** [VeritasOS/netbackup-api-code-samples#80]
I've downloaded d Module and try to crn NetBackup command but get d below error

![image](https://user-images.githubusercontent.com/69708851/93205135-f52f3480-f774-11ea-8fff-eb5c38e452f4.png)

Thanks 
Kavya

**Comment by JC-Cheney** [comment]
You don't appear to be specifying a username or password

./Get-NB-Jobs.ps1 -nbmaster "nb-master.example.com" -username "administrator" -password "secret"
