### ISSUE TITLE
Jobs list empty

### ISSUE THREAD

**Issue by raelbsd** [VeritasOS/netbackup-api-code-samples#88]
Hi, I'm trying the get job's samples (both python and powershell) and I had any issues in the call, but I can't get any jobs (there are plenty). The data list is empty no matter what I try.
I got an API key but it's the same. I've tried setting the query_params as saw in a previous issue but no luck.
Did I missed something?
Thanks in advance

**Comment by tlkrinke** [comment]
what http status code did you get?
My guess is that you dont have permission to view the jobs.

**Comment by raelbsd** [comment]
I'm getting 200 on the requests.get in get_netbackup_jobs. I can view the jobs with my user thru the Netbackup Administration Console.

**Comment by tlkrinke** [comment]
The NetBackup Admin Console is not relevant here - RBAC is not used in the NetBackup Admin Console.  Only the web UI and the APIs are relevant here.   If you are getting a status 200 but no records, you most likely do not have permissions in RBAC.

You can view your RBAC permissions in the web UI

**Comment by raelbsd** [comment]
Thanks, we wasn't using the web ui, now it's working.

**Comment by tlkrinke** [comment]
Glad it worked for you
